In [1]:
#创建元组最简单的方式
tup=4,5,6
tup

(4, 5, 6)

In [2]:
#创建复杂表达式定义的元组，最好放在圆括号内
nested_tup=(4,5,6),(7,8)
nested_tup

((4, 5, 6), (7, 8))

In [3]:
#tuple可以将任意序列或迭代器转换成元组
tuple([4,0,2])

(4, 0, 2)

In [4]:
tup=tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [6]:
#通过[]访问，下标从0开始
tup[0]

's'

In [8]:
#用+连接元组
(4,None,'foo')+(6,0)+('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [9]:
#元组乘以一个整数，会将元组复制串联起来
('foo','bar')*4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

In [11]:
tup=(4,5,6)
a,b,c=tup
b

5

In [13]:
tup=4,5,(6,7)
a,b,(c,d)=tup
d

7

In [14]:
#替换两个数的值
a,b=1,2
b,a=a,b
b

1

In [15]:
#变量拆分用来迭代元组或列表序列
seq=[(1,2,3),(4,5,6),(7,8,9)]
for a,b,c in seq:
    print('a={0},b={1},c={2}'.format(a,b,c))

a=1,b=2,c=3
a=4,b=5,c=6
a=7,b=8,c=9


In [16]:
#元组更高级的拆分
values=1,2,3,4,5
a,b,*rest=values
a,b

(1, 2)

In [17]:
rest

[3, 4, 5]

In [20]:
a,b,*_=values
b

2

In [21]:
a=(1,2,3,3,3,4,2)
a.count(2)

2

In [23]:
a_list=[2,3,7,None]
tup=('foo','bar','baz')
b_list=list(tup)
b_list

['foo', 'bar', 'baz']

In [25]:
b_list[2]='xin'

In [26]:
b_list

['foo', 'bar', 'xin']

In [27]:
#list函数常用来在数据处理中实体化迭代器或生成器
gen=range(10)
gen

range(0, 10)

In [28]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
b_list.append('dwarf')
b_list

['foo', 'bar', 'xin', 'dwarf']

In [30]:
b_list.insert(1,'red')
b_list

['foo', 'red', 'bar', 'xin', 'dwarf']

In [31]:
b_list.pop(2)

'bar'

In [32]:
b_list

['foo', 'red', 'xin', 'dwarf']

In [33]:
#列表连接
[4,None,'foo']+[7,8,(2,3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [34]:
x=[4,None,'foo']
x.extend([7,8,(2,3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

In [36]:
#排序
a=[7,2,5,1,3]
a.sort()
a

[1, 2, 3, 5, 7]

In [37]:
#二级排序
b=['saw','small','he','foxes','six']
b.sort(key=len)
b

['he', 'saw', 'six', 'small', 'foxes']

In [42]:
#bisect模块
import bisect
c=[1,2,2,2,3,4,7]
bisect.bisect(c,2)

4

In [43]:
c

[1, 2, 2, 2, 3, 4, 7]

In [44]:
bisect.bisect(c,5)

6

In [48]:
bisect.insort(c,6)
c

[1, 2, 2, 2, 3, 4, 6, 6, 6, 6, 7]

In [50]:
#切片
seq=[7,2,3,7,5,6,0,1]
seq[1:5]

[2, 3, 7, 5]

In [51]:
#切片也可以被赋值
seq[3:4]=[6,3]
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [52]:
#start和stop都可以被忽略，分别默认开头和结尾
seq[:5]

[7, 2, 3, 6, 3]

In [53]:
seq[3:]

[6, 3, 5, 6, 0, 1]

In [54]:
seq[-4:]

[5, 6, 0, 1]

In [55]:
seq[-6:-2]

[6, 3, 5, 6]

In [56]:
#第二个冒号后面使用step
seq[::2]

[7, 3, 3, 6, 1]

In [57]:
#将列表或元组颠倒起来
seq[::-1]

[1, 0, 6, 5, 3, 6, 3, 2, 7]

In [58]:
#将key和value互换
some_list=['foo','bar','baz']
mapping={}
for i ,v in enumerate(some_list):
    mapping[v]=i
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

In [59]:
sorted([7,1,2,6,0,3,2])

[0, 1, 2, 2, 3, 6, 7]

In [60]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [61]:
#zipped函数
seq1=['foo','bar','baz']
seq2=['one','two','three']
zipped=zip(seq1,seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [62]:
seq3=[False,True]
list(zip(seq1,seq2,seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [63]:
#反转
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [64]:
#创建字典
empty_dict={}
d1={'a':'some value','b':[1,2,3,4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [65]:
d1[7]='an integer'
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [66]:
#del删除方法和pop方法
d1[5]='some value'
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [68]:
del d1[5]
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [69]:
list(d1.keys())

['a', 'b', 7]

In [70]:
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [71]:
#字典融合
d1.update({'b':'foo','c':'12'})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': '12'}

In [73]:
mapping=dict(zip(range(5),reversed(range(5))) )
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [74]:
set([2,2,2,1,3,3])


{1, 2, 3}

In [75]:
{2,2,2,1,3,3}


{1, 2, 3}

In [76]:
a={1,2,3,4,5}
b={3,4,5,6,7,8}
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [77]:
a|b

{1, 2, 3, 4, 5, 6, 7, 8}

In [78]:
#交集
a.intersection(b)

{3, 4, 5}

In [79]:
a&b

{3, 4, 5}

In [81]:
c=a.copy()
c|=b
c

{1, 2, 3, 4, 5, 6, 7, 8}

In [82]:
d=a.copy()
d&=b
d

{3, 4, 5}

In [83]:
my_data=[1,2,3,4]
my_set={tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [84]:
a_set={1,2,3,4,5}
{1,2,3}.issubset(a_set)

True

In [85]:
a_set.issuperset({1,2,3})

True

In [86]:
#集合的内容相同时，集合才对等:
{1,2,3}=={2,1,3}

True

In [87]:
strings=['a','as','bat','car','dove','python']
[x.upper() for x in strings if len(x)>2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [88]:
#获得字符串的长度
unique_lengths={len(x) for x in strings}
unique_lengths

{1, 2, 3, 4, 6}

In [89]:
#使用map函数
set(map(len,strings))

{1, 2, 3, 4, 6}

In [90]:
#
loc_mapping={val:index for index,val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [97]:
#嵌套列表
all_data=[['John','Emily','Michael','Mary','Steven'],
          ['Maria','Juan','Javier','Natalia','Pilar']]
names_of_interset=[]
for names in all_data:
    enough_es=[name for name in names if name.count('a')>=2]
    names_of_interset.extend(enough_es)
names_of_interset

['Maria', 'Natalia']

In [98]:
#函数，用def声明，用return返回值
def my_function(x,y,z=1.5):
    if z>1:
        return z*(x+y)
    else:
        return z/(x+y)
my_function(5,4)


13.5

In [102]:
def func():
    a=[]
    for i in range(5):
        a.append(i)
    return a
func()

[0, 1, 2, 3, 4]

In [104]:
#在函数中修改全局变量，必须用global声明
a=None
def bind_a_variable():
    global a
    a=[]
bind_a_variable()

In [105]:
a

[]

In [107]:
#函数可以返回多个值
def f():
    a=5
    b=6
    c=7
    return a,b,c
a,b,c=f()
print('0:{0}，1：{1}，2:{2}'.format(a,b,c))

0:5，1：6，2:7


In [108]:
#数据清洗类的工作，去除空白符、删除各种标点符号、正确的大小写
#正确的做法是使用内置的字符串方法和正则表达式re模块。
states=['Alabama','Georia!','Georgia','groria','Fl0rIda','south  carolina##',
        'West virginia?']


In [111]:
import re
def clean_strings(strings):
    result=[]
    for value in strings:
        value=value.strip()
        value=re.sub('[!#?]','',value)
        value=value.title()
        result.append(value)
    return result
clean_strings(states)

['Alabama',
 'Georia',
 'Georgia',
 'Groria',
 'Fl0Rida',
 'South  Carolina',
 'West Virginia']

In [115]:
#多函数模式
def remove_punctuation(value):
    return re.sub('[!#?]','',value)
clean_ops=[str.strip,remove_punctuation,str.title]
def clean_strings(strings,ops):
    result=[]
    for value in strings:
        for function in ops:
            value=function(value)
        result.append(value)
    return result
clean_strings(states,clean_ops)

['Alabama',
 'Georia',
 'Georgia',
 'Groria',
 'Fl0Rida',
 'South  Carolina',
 'West Virginia']

In [ ]:
#匿名函数
def short_function(x):
    return x*2
equiv_anon=lambda x:x*2

In [116]:
strings=['foo','card','bar','aaaa','abab']
strings.sort(key=lambda x:len(set(list(x))))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [117]:
#柯里化
def add_numbers(x,y):
    return x+y
add_five=lambda y:add_numbers(5,y)
from functools import partial
add_five=partial(add_numbers,5)


In [118]:
some_dict={'a':1,'b':2,'c':3}
for key in some_dict:
    print(key)

a
b
c


In [120]:
dict_iterator=iter(some_dict)
dict_iterator

In [133]:
def squares(n=10):
    print('Generatings squares from 1 to{0}'.format(n*2))
    for index in range(index,n+1):
        yield index**2
gen=squares()
gen


<generator object squares at 0x0000000004D37CF0>

In [138]:
#itertools
import itertools
first_letter=lambda x:x[0]
names=['Alan','Adam','Wes','Will','Albert','Steven']
for letter,names in itertools.groupby(names,first_letter):
    print(letter,list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [139]:
import sys
sys.getdefaultencoding()

'utf-8'

In [142]:
import numpy as np
my_arr=np.arange(1000000)
my_list=list(range(100000))

In [143]:
import numpy as np
data=np.random.randn(2,3)
data

array([[ 1.33416729,  0.08707772,  1.63433094],
       [-0.69620652,  1.25054449,  0.70055345]])

In [144]:
data*10

array([[13.34167286,  0.87077721, 16.34330943],
       [-6.96206519, 12.50544487,  7.00553454]])

In [145]:
data+data

array([[ 2.66833457,  0.17415544,  3.26866189],
       [-1.39241304,  2.50108897,  1.40110691]])

In [146]:
data.shape

(2, 3)

In [147]:
data.dtype

dtype('float64')

In [149]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [150]:
#全0数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [151]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [152]:
np.empty((2,3,2))

array([[[1.08e-321, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]]])

In [153]:
arr1=np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

In [154]:
#转换类型
arr=np.array([1,2,3,4,5])
arr.dtype


dtype('int32')

In [158]:
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [159]:
#数组之间的运算
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [161]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [162]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [163]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [166]:
#数组大小之间的比较会产生布尔值数组
arr2=np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [167]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [168]:
#数组切片
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
arr[5]

5

In [170]:
arr[5:8]

array([5, 6, 7])

In [172]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [173]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [174]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [175]:
#转置
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [176]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [177]:
arr=np.random.randn(6,3)
arr

array([[ 0.58542311, -1.21771605,  0.10767711],
       [ 0.33004873,  0.27491977,  0.75564885],
       [ 0.98536049,  0.13897549,  1.99364834],
       [-0.49619384, -0.6284392 , -0.06818788],
       [ 1.00286173, -2.41936428, -0.47234882],
       [ 0.08779575,  1.6705526 ,  0.30390802]])

In [179]:
np.dot(arr.T,arr)

array([[ 2.68223576, -2.45299401,  1.86371561],
       [-2.45299401, 10.61673279,  2.04702105],
       [ 1.86371561,  2.04702105,  4.87735633]])

In [181]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [182]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [185]:
#聚类统计
arr=np.random.randn(5,4)
arr

array([[ 0.64278263,  0.93082621, -0.17535946, -1.13389759],
       [ 0.02392463, -2.10612413,  0.41378288, -0.78554376],
       [-0.095916  ,  0.40819261,  1.06002332, -0.71445624],
       [ 0.25598855, -0.73703579, -1.73871338,  1.40448846],
       [-0.41771545, -1.16510642,  0.16387352, -0.96715033]])

In [186]:
arr.mean()

-0.23665678668221793

In [187]:
arr.sum()

-4.7331357336443585

In [188]:
#唯一
ints=np.array([3,3,3,3,2,2,1,4])
np.unique(ints)


array([1, 2, 3, 4])

In [194]:
#线性代数
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,2],[-1,7],[8,9]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
y

array([[ 6,  2],
       [-1,  7],
       [ 8,  9]])

In [196]:
x.dot(y)

array([[28, 43],
       [67, 97]])

In [197]:
#伪随机数生成
samples=np.random.normal(size=(4,4))
samples

array([[-0.2709737 ,  0.04657909, -0.0102372 ,  1.76773637],
       [ 0.70875325, -0.00984184,  1.08533683, -1.63378896],
       [ 2.17363766,  0.51396356, -0.14255026,  0.89641326],
       [ 1.27157514,  0.72396345,  1.0999926 ,  0.82716957]])